- name: variables from the files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
    - name: prin the course information
      ansible.builtin.debug:
        msg: "Hello Iam learning {{Course}}, Duration : {{Duration}}, Trainer : {{Trainer}}"